const pistaImages = {
    "Abu Dabi": require("../Imagenes/Imagenes carreras/abudhabi.jpg"),
    "Melbourne": require("../Imagenes/Imagenes carreras/australia.jpg"),
    "Austria": require("../Imagenes/Imagenes carreras/austria.jpg"),
    "Azerbaiyán": require("../Imagenes/Imagenes carreras/azerbaijan.jpg"),
    "Barein": require("../Imagenes/Imagenes carreras/bahrein.jpg"),
    "Belgica": require("../Imagenes/Imagenes carreras/belgium.jpg"),
    "Brasil": require("../Imagenes/Imagenes carreras/brazil.jpg"),
    "Canadá": require("../Imagenes/Imagenes carreras/canada.jpg"),
    "China": require("../Imagenes/Imagenes carreras/china.jpg"),
    "Emilia-Romagna": require("../Imagenes/Imagenes carreras/emiliaromagna.jpg"),
    "Gran Bretaña": require("../Imagenes/Imagenes carreras/greatbritain.jpg"),
    "Hungria": require("../Imagenes/Imagenes carreras/hungary.jpg"),
    "Italia": require("../Imagenes/Imagenes carreras/italy.jpg"),
    "Japon": require("../Imagenes/Imagenes carreras/japan.jpg"),
    "Las Vegas": require("../Imagenes/Imagenes carreras/lasvegas.jpg"),
    "México": require("../Imagenes/Imagenes carreras/mexico.jpg"),
    "Miami": require("../Imagenes/Imagenes carreras/miami.jpg"),
    "Mónaco": require("../Imagenes/Imagenes carreras/monaco.jpg"),
    "Países Bajos": require("../Imagenes/Imagenes carreras/netherlands.jpg"),
    "Catar": require("../Imagenes/Imagenes carreras/qatar.jpg"),
    "Arabia Saudita": require("../Imagenes/Imagenes carreras/saudiarabia.jpg"),
    "Singapur": require("../Imagenes/Imagenes carreras/singapore.jpg"),
    "España": require("../Imagenes/Imagenes carreras/spain.jpg"),
    "Estados_Unidos": require("../Imagenes/Imagenes carreras/usa.jpg")
};
