# Generated by Django 5.0.8 on 2025-01-25 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('kilometros', models.FloatField()),
                ('pais', models.CharField(max_length=500)),
                ('ciudad', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='app.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='EstrategiaPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategia_piezas', to='app.estrategia')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategia_piezas', to='app.pieza')),
            ],
        ),
        migrations.AddField(
            model_name='estrategia',
            name='pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='app.pista'),
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('cantVueltas', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='app.estrategia')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='app.pista')),
            ],
        ),
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetrias', to='app.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TimeField()),
                ('numVuelta', models.IntegerField()),
                ('telemetria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app.telemetria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.BigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('apellido', models.CharField(blank=True, max_length=500, null=True)),
                ('legajo', models.BigIntegerField(blank=True, null=True)),
                ('contrasenia', models.CharField(blank=True, max_length=500, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app.usuario')),
            ],
        ),
    ]
