# Generated by Django 5.0.10 on 2025-01-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrategia',
            name='nombre',
            field=models.CharField(choices=[('Lluvia', 'Lluvia'), ('Viento', 'Viento'), ('Seco', 'Seco')], max_length=500),
        ),
        migrations.AlterField(
            model_name='registro',
            name='valor',
            field=models.CharField(max_length=500),
        ),
    ]
