# Generated by Django 5.0.10 on 2025-01-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_estrategia_nombre_alter_registro_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pista',
            name='kilometros',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
