# Generated by Django 5.0.10 on 2025-02-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usuario_managers_remove_usuario_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
