# Generated by Django 5.0.10 on 2025-02-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
