# Generated by Django 5.0.10 on 2025-02-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
