# Generated by Django 5.0.10 on 2025-02-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenia',
            field=models.TextField(blank=True, db_column='contrasenia', null=True),
        ),
    ]
